# Only add custom fishes to the loot table if the original loot was a fish
# Example:
# Fishing throws a raw cod -> re-roll the loot table now with only custom fishes and the original result -> result can vary between vanilla and custom fishes
# Fishing throws an enchanted book -> result: enchanted book
#
# When it's disabled:
# Fishing throws a pufferfish -> re-roll the loot table now with only custom fishes and the original result -> result can vary...
# Fishing throws a tripwire -> re-roll the loot table now with only custom fishes and the original result -> result can vary...
append_to_vanilla_fish_loot: true

# Value between 0 and 1 (0 disables the custom fish obtaining)
# 1 -> Fully replaces the vanilla fishing table
custom_fish_loot_weight: 0.5

# Fish weight measure suffix
weight_measure: "oz"

# Custom fishes
fishes:
  # How to add a custom fish:
  # First, you need to replicate the following structure:
  # - id: string
  #   display_name: string            Item display name (You can use color codes)
  #   lore: string[]                  Item lore (You can use color codes)
  #   model_data: number (optional)   Item custom model data (for custom textures)
  #   material: string                Item type/material (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
  #   fish_weight: (optional)
  #     min: (number)                 Set to 1 by default
  #     max: (number)                 Set to 10 by default
  #   loot_weight: number (optional)  Chance of the loot (more weight = more chance) Set to 1 by default
  #   qualities: (optional)
  #     - id: string                  Id of an existing quality
  #       weight: number              Modify the weight for an existing quality (only applicable to this fish)

  - id: "dndcraft:example_fish"
    display_name: "&eExample Fish"
    lore:
      - "&bA really cool fish"
    model_data: 1
    material: COD
    fish_weight:
      min: 3
      max: 10
    loot_weight: 3
  - id: "dndcraft:troublesome_trout"
    display_name: "&bTroublesome Trout"
    lore:
      - "A slick devilish fish"
    material: SALMON
    fish_weight:
      min: 2
      max: 15
    loot_weight: 2
    qualities: # In this example always throws the legendary quality. (NOTE: You don't need to put all the qualities in this param. You can just modify whatever you want)
      - id: "dndcraft:legendary_quality"
        weight: 15
      - id: "dndcraft:good_quality"
        weight: 0
      - id: "dndcraft:poor_quality"
        weight: 0
  - id: "dndcraft:mullet"
    display_name: "&eMullet"
    lore:
      - "&7A large red fish"
    material: SALMON
    fish_weight:
      min: 17
      max: 32
    loot_weight: 1
  - id: "dndcraft:alaska_pollock"
    display_name: "&aAlaska Pollock"
    lore:
      - ""
    material: COD
    fish_weight:
      min: 3
      max: 8
    loot_weight: 3
  - id: "dndcraft:clownfish"
    display_name: "&eClownfish"
    lore:
      - "&7Among the most recognizable"
      - "&7of all reef-dwellers"
    material: TROPICAL_FISH
    fish_weight:
      min: 6
      max: 8
    loot_weight: 5

# Default quality threshold for every fish. You can customize it on every fish in the "qualities" param
qualities:
  - id: "dndcraft:poor_quality"
    display: "&7&lPoor Quality"
    weight: 3
  - id: "dndcraft:good_quality"
    display: "&6&lGood Quality"
    weight: 2
  - id: "dndcraft:legendary_quality"
    display: "&4&lLegendary Quality"
    weight: 1

gui_titles:
  fish_rank: "Fish Rank"
  appraise_fish: "Appraise Fish"