name: MoreFishes
version: '${project.version}'
main: me.monkeykiller.morefishes.MoreFishes
api-version: 1.17
authors: [ MonkeyKiller ]

commands:
  morefishes:
    aliases: [ mf, fishes ]
    description: MoreFishes main command
    permission: morefishes.command
    usage: |
      §cUsage:
      §c/<command> give <id> [count] [weight]
      §c/<command> appraise
      §c/<command> rank
      §c/<command> reload
  appraise:
    description: MoreFishes appraise command
    permission: morefishes.command.appraise
  fishrank:
    description: MoreFishes rank command
    permission: morefishes.command.fishrank
permissions:
  morefishes.command.give:
    description: Allows access to give custom fishes
    default: op
  morefishes.command.appraise:
    description: Allows access to appraise custom fishes
    default: op
  morefishes.command.reload:
    description: Allows access to reload the plugin configurations
    default: op
  morefishes.command.fishrank:
    description: Allows access to see the fish rank gui
